MDScreen:
    name:'payment_page'
    BoxLayout:
        orientation: 'vertical'

        MDIconButton:
            icon: "arrow-left"
            pos_hint: {"center_y": .91}
            user_font_size: "20sp"
            theme_text_color: "Custom"
            text_color: rgba(71, 92, 119, 255)
            on_release: app.payment_page_backButton()
#                root.manager.transition.direction = "right"
#                root.manager.current = "slot_booking"